name: Deploy testground

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build project
        run: npm install && npm run build:testground

      - name: Reset project
        run: git reset --hard

      - name: Deploy to remote
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DEPLOY_REMOTE_SERVER }}
          username: ${{ secrets.DEPLOY_REMOTE_USER }}
          password: ${{ secrets.DEPLOY_REMOTE_PASSWORD }}
          local_path: "./dist-testground/*"
          remote_path: ${{ secrets.DEPLOY_REMOTE_PATH }}
          sftp_only: true
          sftpArgs: "-o ConnectTimeout=10"
