name: Deploy testground

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build project
        run: npm install && npm run build:testground

      - name: Deploy to remote
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.DEPLOY_REMOTE_SERVER }}
          ftp-username: ${{ secrets.DEPLOY_REMOTE_USER }}
          ftp-password: ${{ secrets.DEPLOY_REMOTE_PASSWORD }}
          local-dir: dist-testground
          git-ftp-args: --insecure
